name: Automatic update

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "adopt"
        java-version: "17"
    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f main/requirements.txt ]; then pip install -r main/requirements.txt; fi
    - name: Update outputs
      run: python3 main/main.py
    - name: Push updates
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        commit_message: Automatic update commit
