name: Automatic update

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "microsoft"
        java-version: "17"
    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip wheel setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update outputs
      run: python3 src/main.py
    - name: Push updates
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        commit_message: Automatic update commit
